name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 */6 * * *' # Runs every 6 hours
  workflow_dispatch: # Allows manual triggering

jobs:
  update-readme:
    name: WakaTime Readme
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Update WakaTime stats
        uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          
          # Customization options
          SHOW_TITLE: true
          SECTION_NAME: waka
          API_BASE_URL: https://wakatime.com/api
          REPOSITORY: Skaikru0518/Skaikru0518
          
          # Visual settings
          BLOCKS: =>  # Custom bar characters
          CODE_LANG: text # Code block style (txt, md, json)
          TIME_RANGE: last_7_days # Options: last_7_days, last_30_days, last_year, all_time
          LANG_COUNT: 3 # Number of languages to show
          SHOW_TIME: true # Show time spent
          SHOW_TOTAL: true # Show total coding time
          SHOW_MASKED_TIME: true # Hide exact time values
          STOP_AT_OTHER: true # Stop listing at 'Other' category
          IGNORED_LANGUAGES: YML, Git, BASH, Bash, bash

